security:
  oauth2:
    client:
 # local host id and secret
 #      clientId: 4e78f0c4fc7f457ecaf4
 #      clientSecret: 301d39e18bc2bff6325751e3c152270e66ab7595
 # Azure host id and secret
       clientId: 3ed9384025346179f2bb
       clientSecret: 269f5095cbb43f9daf2ce14c0cfde5e1e865e874
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false 